### ISSUE TITLE
v0.0.x to v0.1.x

### ISSUE THREAD

**Issue by erhant** [erhant/circomkit#42]
- [ ] #40 (without scope-hoisting)
- [ ] #38 
- [ ] #26 
- [ ] #39 which returns an array of entries, compatible with `console.table` for the CLI
- [ ] #41 (not sure about this 100%)
- [ ] Make SnarkJS a peer-dependency
- [ ] Use PNPM
